### ISSUE TITLE
Build problem: How can I specifiy a version during build

### ISSUE THREAD

**Issue by guidoffm** [opsdis/icinga2-exporter#10]
While building I get a mesage complaining "dirty_dev" is an invalid version. How can I fix this?

**Comment by guidoffm** [comment]
Thank you for this information. If you have a release binary would you consider to publish it to the Python package library to allow easier installation with pip?

**Comment by thenodon** [comment]
That would good idea. Should be able to add that to the build pipeline. Currently we use travis-ci.org but we should look into github actions. Its on the todo list :). You are more than welcome to contribute if you have the time.

**Comment by thenodon** [comment]
Build pipeline now upload to pypi.org
