### ISSUE TITLE
Illegal char in metric name

### ISSUE THREAD

**Issue by msafdal** [opsdis/icinga2-exporter#11]
Illegal char not sanitized which leads to no scraping of the target.

curl -s localhost:9638/metrics?target=xxx | /usr/local/bin/promtool check metrics
error while linting: text format parsing error in line 2: expected float as value, got "'reserve_processor_usage'_ratio{hostname=\"xxx\","

Fix:
perfdata.py
prometheus_key = prometheus_key.replace('\'', '_')

**Comment by guidoffm** [comment]
I get these errors too:

`icinga2_ivu_net_linux_lo_rxerrs=0.00b|eth0_txbyt_bytes{hostname="awsdfisradbreg4.isr-test.comp.db.de", service="network", agent="agent", cpu_usage_crit="90", cpu_usage_warn="80", disable_check_updates="false", os="linux"} 294.0`

And for Windows servers:

```
icinga2_ivu_disk_windows_'\\?\volume{b1a3abdb_18b6_11e9_813c_806e6f6e6963}\_free_percent'_ratio{hostname="AWSDFISRATS0003.bku.db.de", service="disk", agent="agent", cpu_usage_crit="90", cpu_usage_warn="80", disable_check_updates="false", os="windows"} 0.28
icinga2_ivu_disk_windows_'d:\_free'_bytes{hostname="AWSDFISRATS0003.bku.db.de", service="disk", agent="agent", cpu_usage_crit="90", cpu_usage_warn="80", disable_check_updates="false", os="windows"} 16129964428.4928
```

**Comment by thenodon** [comment]
Thanks to @guidoffm for fixing this issue.
