### ISSUE TITLE
nssl.SSLError

### ISSUE THREAD

**Issue by Nudin** [opsdis/icinga2-exporter#22]
When running as in the example config, I get SSL-errors:

```
{"timestamp": "2021-07-23T12:19:50.527116Z", "level": "INFO", "name": "icinga2-exporter", "message": "http://localhost:9638/metrics?target=icinga2"}
{"timestamp": "2021-07-23T12:19:50.527286Z", "level": "INFO", "name": "icinga2-exporter", "message": "Collect metrics", "target": "icinga2"}
[2021-07-23 12:19:50,546] 127.0.0.1:56630 GET /metrics 1.1 200 0 19830
{"timestamp": "2021-07-23T12:19:50.547602Z", "level": "ERROR", "name": "asyncio", "message": "SSL error in data received\nprotocol: <asyncio.sslproto.SSLProtocol object at 0x7fd6592306a0>\ntransport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>", "exc_info": "Traceback (most recent call last):\n  File \"/usr/lib/python3.7/asyncio/sslproto.py\", line 526, in data_received\n    ssldata, appdata = self._sslpipe.feed_ssldata(data)\n  File \"/usr/lib/python3.7/asyncio/sslproto.py\", line 207, in feed_ssldata\n    self._sslobj.unwrap()\n  File \"/usr/lib/python3.7/ssl.py\", line 767, in unwrap\n    return self._sslobj.shutdown()\nssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)"}
```

Seem like this [bug](https://github.com/aio-libs/aiohttp/issues/3535), but not sure how to fix this in production systems.

**Comment by thenodon** [comment]
Look like you use http instead of https - is this what you want?

**Comment by thenodon** [comment]
Can you describe a bit more about your environment? The bug you refer to seems to behave differently depending on Python versions. What version are you using (Im running 3.8)? What is the setup of your icinga2?

**Comment by thenodon** [comment]
Have done some testing and can not reproduce the error while just running as quart webapp on python 3.8. But running with gunicorn I get this error, even after upgrading all dependency packages. Tested with hypercorn, 0.11.2, and that worked fine. 
pip install hypercorn 
hypercorn "wsgi:create_app('./my_config.yml')"

**Comment by Nudin** [comment]
I was just running it in development mode: `python3 -m  icinga2_exporter -f config.yml` with python version 3.7.3. I now tried with hypercorn – that worked. (Feel free to close this ticket)

**Comment by thenodon** [comment]
Thanks for the feedback. Did you try development mode with python 3.8?

**Comment by thenodon** [comment]
Closing this issue due to lack of feedback
