### ISSUE TITLE
Scrape all Performancedata

### ISSUE THREAD

**Issue by fl0wx** [opsdis/icinga2-exporter#34]
Hey,

is it possible to scrape all perfdata from all services at once ? or at least an easy way to scrape everything? I have many hosts and dont want to configure them in the prometheus configuration.

Another Question: Is it possible to exclude service vars ?

Thanks and kr 
fl0wx

**Comment by thenodon** [comment]
I understand that you like to avoid to create every host in your prometheus configuration. I suggest you give https://github.com/opsdis/monitor-promdiscovery a try. It is target for this use case and work with prometheus service discovery.
When it comes to manages vars I will look into that.

**Comment by thenodon** [comment]
Closing due to lack of feedback
