### ISSUE TITLE
Add project to Helm chart repository

### ISSUE THREAD

**Issue by Kenzi007220** [opsdis/icinga2-exporter#43]
Good day.
Can this project be included in helm chart repository? Since some dependencies are now missing in Debian repository, we are not allowed to install it. It would be great if you could prepare this feature.
Thanks

**Comment by thenodon** [comment]
Hi @Kenzi007220 sound like a great idea. I have limited time to work on this, but you, or someone else, are more than welcome to implement it and make a PR.

**Comment by thenodon** [comment]
Closed due to inactivity
